server.port=8081
spring.application.name=user-service

spring.kafka.bootstrap-servers=10.242.134.57:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer
